import { useEffect, useState } from 'react';
import { supabase } from './lib/supabase';
type UserRow={id:string;email:string;name:string;role:string;active:boolean;last_sign_in_at:string|null;family_cost_permissions:number[]};
const families=[['Bebidas',1],['Suplementos',2],['Fertilizantes',3]] as const;
export default function RegisteredUsers(){
 const [rows,setRows]=useState<UserRow[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[page,setPage]=useState(1),[hasMore,setHasMore]=useState(false),[selected,setSelected]=useState<UserRow|null>(null),[module,setModule]=useState<'users'|'permissions'>('users');
 useEffect(()=>{let active=true;setLoading(true);setError('');setRows([]);
 (async()=>{try{
  const {data}=await supabase!.auth.getSession();
  if(!data.session)throw new Error('Entre novamente no Rocket.');
  const response=await fetch('/api/admin/users?page='+page,{headers:{Authorization:'Bearer '+data.session.access_token},cache:'no-store'});
  const result=await response.json();if(!response.ok)throw new Error(result.error||'Não foi possível carregar os usuários.');
  if(active){setRows(result.users);setHasMore(result.has_more);}
 }catch(e){if(active)setError(e instanceof Error?e.message:'Falha de conexão.');}finally{if(active)setLoading(false);}})();
 return()=>{active=false;};},[page]);
 const saveFamilies=async(user:UserRow,familyIds:number[])=>{try{const {data}=await supabase!.auth.getSession();if(!data.session)throw new Error('Entre novamente no Rocket.');const response=await fetch('/api/admin/users',{method:'PUT',headers:{Authorization:'Bearer '+data.session.access_token,'Content-Type':'application/json'},body:JSON.stringify({user_id:user.id,family_ids:familyIds})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Não foi possível salvar.');setRows(current=>current.map(row=>row.id===user.id?{...row,family_cost_permissions:familyIds}:row));}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar permissões.');}};
 return <section><div className="internalMenu"><button className="roundAction" onClick={()=>setModule('users')} title="Usuários">♙</button><button className="roundAction" onClick={()=>setModule('permissions')} title="Permissões">⚙</button></div><p role="status">{loading?'Carregando usuários…':error}</p>{module==='users'&&<div className="card tableWrap"><table><thead><tr><th>Nome</th><th>E-mail</th><th>Perfil</th><th>Status</th><th>Último acesso</th><th>Permissões</th></tr></thead><tbody>{rows.map(user=><tr key={user.id}><td>{user.name||'—'}</td><td>{user.email}</td><td>{user.role}</td><td>{user.active?'Ativo':'Sem acesso ativo'}</td><td>{user.last_sign_in_at?new Date(user.last_sign_in_at).toLocaleString('pt-BR'):'Ainda não acessou'}</td><td><button className="roundAction" title="Gerir permissões" onClick={()=>{setSelected(user);setModule('permissions')}}>⚙</button></td></tr>)}{!loading&&!error&&!rows.length&&<tr><td colSpan={6}>Nenhum usuário cadastrado.</td></tr>}</tbody></table></div>}{module==='permissions'&&<div className="card"><h3>{selected?`Permissões — ${selected.name||selected.email}`:'Selecione um usuário'}</h3>{selected&&<><div className="familyPermissions">{families.map(([label,id])=><label key={id}><input type="checkbox" checked={selected.role==='Admin'||selected.family_cost_permissions.includes(id)} disabled={selected.role==='Admin'} onChange={e=>{const ids=e.target.checked?[...selected.family_cost_permissions,id]:selected.family_cost_permissions.filter(value=>value!==id);saveFamilies(selected,ids);setSelected({...selected,family_cost_permissions:ids})}}/>{label}</label>)}</div><button className="secondary" type="button" title="Redefinir senha no próximo acesso">↻ Redefinir senha</button></>}</div>}</section>;
}
